services:
  # Spring Boot Backend Service
  - type: web
    name: family-tree-backend
    runtime: docker
    plan: free
    dockerContext: ./FamilyDataTree
    dockerfilePath: ./FamilyDataTree/Dockerfile
    envVars:
      - key: SPRING_NEO4J_URI
        sync: false
      - key: SPRING_NEO4J_AUTHENTICATION_USERNAME
        sync: false
      - key: SPRING_NEO4J_AUTHENTICATION_PASSWORD
        sync: false

  # React Frontend Static Site
  - type: web
    name: family-tree-frontend
    runtime: static
    rootDir: client
    buildCommand: npm install && npx craco build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://family-tree-backend-v207.onrender.com/api
      - key: GENERATE_SOURCEMAP
        value: false
