spring.application.name=FamilyDataTree
logging.level.org.springframework.ai=DEBUG

server.port=${PORT:8081}

spring.neo4j.uri=${SPRING_NEO4J_URI:neo4j+s://883d9998.databases.neo4j.io}
spring.neo4j.authentication.username=${SPRING_NEO4J_AUTHENTICATION_USERNAME:883d9998}
spring.neo4j.authentication.password=${SPRING_NEO4J_AUTHENTICATION_PASSWORD:3VKL7RyUPpYBYWaaIBXoImZbZh9c14HisMMYg-7jU9w}

spring.data.neo4j.uri=${SPRING_NEO4J_URI:neo4j+s://883d9998.databases.neo4j.io}
spring.data.neo4j.username=${SPRING_NEO4J_AUTHENTICATION_USERNAME:883d9998}
spring.data.neo4j.password=${SPRING_NEO4J_AUTHENTICATION_PASSWORD:3VKL7RyUPpYBYWaaIBXoImZbZh9c14HisMMYg-7jU9w}